### ISSUE TITLE
README execution examples do not work as expected

### ISSUE THREAD

**Issue by Alejandro-FA** [jsego/bfgp-pp#18]
When running the **synthesis mode** example of the `README`, the output is placed in the root of the project folder. This is the output of the command:

```
(...)

[INFO] Program file: gripper.prog
[INFO] Experiments file: gripper.out
```

Therefore, running the **validation mode** example (`./main.bin -m validation-prog -p experiments/gripper/gripper.prog -f domains/gripper/validation/easy/`) fails, because the file `experiments/gripper/gripper.prog` does not exist.

Perhaps the issue is related to the `-o gripper` parameter of the synthesis mode command. Executing `./main.bin -m synthesis -l 8 -f domains/gripper/synthesis/ -pgp True` produces the following output instead:

```
(...)

[INFO] Program file: experiments/gripper/synthesis_8_ed_ilc.prog
[INFO] Experiments file: experiments/gripper/synthesis_8_ed_ilc.out
```

**Comment by jsego** [comment]
Validation examples have been updated with the right input program parameter.
